version: "3"
services:
    postgres:
        image: manojishere/postgresdb:v1
        build:
            context: .
            dockerfile: PostgresqlDockerfile    
        networks:
            -   demo_net
        container_name: postgresql_host
        volumes:
            - postgres-data:/var/lib/postgresql/data
        expose:
            - 5432
        ports:
            - 5432:5432
        environment:
            -   "POSTGRES_PASSWORD=docker"
            -   "POSTGRES_USER=docker"
            -   "POSTGRES_DB=docker"
        restart: unless-stopped
# This is my rest api app*****************************************

    lb:
      image : manojishere/nginx:lb
      networks:
          -   demo_net    
      build:
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - "8081:80"
      depends_on:
        - service1
    service1:
        image : manojishere/springboot_with_postgresdb:draft
        build:
          context: .
          dockerfile: Dockerfile
        networks:
            -   demo_net          
        container_name: first_rest_controller       
        ports:
          - "8085:8085"
networks:
    demo_net:
        driver: bridge
volumes:
    postgres-data: